apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
  labels:
    app: testapp
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: testapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: testapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: {{.Values.name}}
        image: {{.Values.image}}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
