apiVersion: v1
kind: Service
metadata:
  name: my-dockerapp-svc
  labels:
    app: dockerapp
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: dockerapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dockerapp
  labels:
    app: dockerapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockerapp
  template:
    metadata:
      labels:
        app: dockerapp
    spec:
      containers:
      - name: {{.Values.name}}
        image: {{.Values.image}}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
